<h1>About this marketing copywriter</h1>
<h3>Meet marketer and copywriter Renae Gregoire<img class="alignright wp-image-2706 size-full" src="http://ineedcopy.com/wp-content/uploads/2011/01/marketing-writer-renae-gregoire.jpg" alt="Hello! I'm marketing writer Renae Gregoire. What marketing content do you need help with?" width="128" height="168" /></h3>
<h4><strong>A copywriting and marketing faux pas?</strong></h4>
<span >As a sales and marketing writer, I know I’m not supposed to talk about “me.” But I also know that if you’re seriously considering tapping into my learning and talent to help you market your business or produce great sales and marketing collateral, you’ll want to know a little more about who I am, as a business and as a person.</span>
<em>I know I would.</em>
<h3>The Write Idea: Who I am, and who I’m not</h3>
<h4><strong>A marketer first, copywriter / marketing writer second. </strong></h4>
<span style="">First and foremost, I’m a marketer. Sales enthusiast. Lover of business, ideas, and the entrepreneurial spirit. Despite much bluster to the contrary, I believe you shouldn’t persuade people to buy products or services they really don’t want. I also believe it’s not in your best interests to try.</span>
I’m not a loud-mouthed, overly enthusiastic, shove-it-down-their-throats kind of marketing copywriter. I believe people want to read, love to buy, but hate to be sold. My goal then, is to educate your buyers. It’s to build trust and confidence. My goal is to help your buyers take the next step in the buying process, and to feel good about doing so!
Second, I’m a copywriter. Direct marketing writer. Marketing communications writer. Business writer. Lover of the written word. I’m admittedly not the most creative head in the business, but I love what I do and it shows. I’m a stickler for grammar, but don’t claim to know everything. I’m not a proofreader; typos occasionally slip by me. I love a well-turned phrase, and crave intelligent writing that opens my eyes–writing that makes me think and helps me grow.
<h3>The Write Idea: What I do</h3>
<h4><strong>Get the right message to the right reader at the right time.</strong></h4>
<span style="">Merge marketing with copywriting and what do you get? The Write Idea: a marketing and copywriting firm that uses the written word to help you market and sell to other businesses, or to intelligent consumers who want to read, love to buy, but hate to be sold. I, through my firm, help you replicate your sales force–even a sales force of one–through marketing and sales collateral like </span><a style="" title="" href="http://ineedcopy.com/copywriting-services/brochure-content-writing/">brochures</a><span style="">, </span><a style="" title="" href="http://ineedcopy.com/copywriting-services/direct-mail-writing/">direct mail letters</a><span style="">, </span><a style="" title="" href="http://ineedcopy.com/copywriting-services/web-content-writing/">Web sites</a><span style="">, </span><a style="" title="" href="http://ineedcopy.com/copywriting-services/brochure-content-writing/">print ads</a><span style="">, </span><a style="" title="Copywriting services" href="http://ineedcopy.com/copywriting-services/">white papers</a><span style="">, </span><a style="" title="Success stories writing" href="http://ineedcopy.com/copywriting-services/success-stories-writing/">success stories</a><span style="">, </span><a style="" title="" href="http://ineedcopy.com/copywriting-services/press-release-writing/">press releases</a><span style="">, </span><a style="" href="http://ineedcopy.com/blog">articles</a><span style=""> and </span><a style="" title="" href="http://ineedcopy.com/copywriting-services/">more</a><span style="">.</span>
I do this by studying your market, your product, your service. By creating marketing and sales messages that match how your customers purchase–from awareness and interest to consideration and sale. By analyzing your typical sales cycle to discover what buyers need to hear, see, and feel during each stage. And then by recommending, writing, and working with you to develop collateral that delivers the right messages to the right buyers at the right times.
Sound good?
<h3>The Write Idea: How to connect</h3>
<h4><strong>Take the next step.</strong></h4>
<span style="">I invite you to explore this website. Browse my </span><a style="" title="" href="http://ineedcopy.com/copywriting-portfolio/" target="">copywriting portfolio</a><span style="">. Learn what my </span><a style="" title="" href="http://ineedcopy.com/testimonials/" target="">satisfied copywriting customers</a><span style=""> say about how I do business. And then, when you’re ready, </span><a style="" title="" href="http://ineedcopy.com/contact-me/" target="">email</a><span style=""> me or give me a call to discuss the particulars of your business or projects.</span>
Discussions are always welcome, always free. And I promise–no hard sale.